name: Update LeetCode Chart
on:
  schedule:
    - cron: '0 2 * * *'   # Runs every day at 02:00 UTC
  workflow_dispatch:
permissions:
  contents: write

jobs:
  build-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests matplotlib

      - name: Generate LeetCode chart
        env:
          LC_USER: NAFTfBr440   # Your LeetCode username
        run: |
          mkdir -p assets
          python scripts/generate_leetcode_chart.py "$LC_USER" assets/leetcode_difficulty.png

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/leetcode_difficulty.png || echo "no changes"
          git commit -m "chore: update leetcode difficulty chart" || echo "no changes to commit"
          git push origin HEAD:main
